### ISSUE TITLE
In Internet Explorer 11 truncated ellipsis do not render - they appear as squares

### ISSUE THREAD

**Issue by seager** [IBM/plex#110]
On Windows 10 Pro version 1709, Internet Explorer 11 version 11.64.16299.0 Update version 11.0.48.

When using the Plex font "IBM Plex Sans", for a line which is truncated due the line being too long, and the CSS text-overflow is set to ellipsis, instead of "..." appearing at the end, three squares appear at the end of the text.

This has been tried on Plex version 5.1, 4.3 and 4.1. In 5.1 and 4.3 the squares show:

![image](https://user-images.githubusercontent.com/12764340/33433608-253b4d14-d5d4-11e7-84b0-482469c650b6.png)

In Plex 4.1 the ellipsis show:

![image](https://user-images.githubusercontent.com/12764340/33433624-3794d28c-d5d4-11e7-9591-8d576043b9c3.png)

I have reproduced the issue using stand alone HTML and the Plex on unpkg.com. In our actual application the fonts and Sass are copied into our distribution using webpack, but because I can reproduce stand-alone it appears to be something in the font.

Here is a ZIP with the tests:
[tests.zip](https://github.com/IBM/type/files/1517959/tests.zip)

`test - 41.html` uses Plex 4.1 and works. `test - 43.html` and `test - 51.html` display the issue in Internet Explorer 11. 

This also does not work in Internet Explorer 11 in Windows 7 Service Pack 1. It does work in the latest Chrome, Firefox and Edge browsers.

Thanks!

**Comment by seejamescode** [comment]
Thanks for doing so much debugging ahead of time, @seager!

Tagging @BoldMonday for help.

**Comment by BoldMonday** [comment]
I've had a quick look and was able to replicate the problem with IE11 on Windows 7.

It can't be a font problem because the very same fonts are used in all three scenarios.

Therefore I suspect it is a css font-loading problem, but I'm not an expert on that.

**Comment by seejamescode** [comment]
Paul provided the screenshots below to help out...

The problem with fonts loading is in the order of `Pi > Latin3 > Latin2 > Latin1`:
![image](https://user-images.githubusercontent.com/7519029/33446802-d9f00eec-d5c6-11e7-9cda-6a24f89891ff.png)

The fix is with fonts loading in the order of `Latin1 > Latin2 > Latin3 > Pi`:
![image](https://user-images.githubusercontent.com/7519029/33446943-41421694-d5c7-11e7-9fb2-e60c3b36e9b1.png)

The problem with this fix is that it will break our solution to #34. @davelab6, have you faced this problem before?

**Comment by nicoxxie** [comment]
Hi, this is an issue impacting multiple teams.  I have verified the same styles and everything works with another font, but just not IBM Plex.

**Comment by joshblack** [comment]
To help isolate this further, I don't believe this issue exists when using the link to Google Fonts CDN, e.g.: `<link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans" rel="stylesheet">`

When accessing this link from a browser, it seems like we get back the following definition:

```css
@font-face {
  font-family: 'IBM Plex Sans';
  font-style: normal;
  font-weight: 400;
  src: local('IBM Plex Sans'), local('IBMPlexSans'), url(https://fonts.gstatic.com/s/ibmplexsans/v2/zYXgKVElMYYaJe8bpLHnCwDKhdHeEw.woff) format('woff');
}
```

This differs from the unpkg reference in that it doesn't include the unicode range and, I believe, provides the full `woff` file.

**Comment by BoldMonday** [comment]
As I illustrated above, I believe this is a css font-loading issue related to split web fonts. Apparently IE handles this stuff differently from other browsers.

Full `woff` and `woff2` files are also included in this repo. From our point of view these fonts are the recommended choice because they contain all features, and full kerning.

Check the contents of `web.zip` in the latest release.
https://github.com/IBM/plex/releases

**Comment by joshblack** [comment]
Totally agreed @BoldMonday 🙂 it's more so that guidance for usage just needs to be tailored, that's all. Was trying to debug the font loading issue as part of our work this sprint with the design core team 👍

**Comment by seejamescode** [comment]
Hey @joshblack, you are looking at the `.woff`, but Google does split `.woff2` as seen here: https://fonts.googleapis.com/css?family=IBM+Plex+Sans:100. Can you confirm that Google’s split contains or does not contain the same bug?

**Comment by eshaseth** [comment]
In IE 11 version 11.914.17763.0, I still see ... as squares . I am using Korean language.
How can I fix this issue?

**Comment by eshaseth** [comment]
@seejamescode could you please reopen and look into this issue
@joshblack
