### ISSUE TITLE
UFO source files are damaged

### ISSUE THREAD

**Issue by BoldMonday** [IBM/plex#136]
Current UFO source files appear to be damaged, and cannot be opened.

When comparing the UFO files downloaded from this repository with the ones that we delivered there is a huge difference in file size.

**from GitHub:**
<img width="793" alt="github" src="https://user-images.githubusercontent.com/13793769/36541379-fbecd5da-17dd-11e8-855b-73d0d90d4364.png">

**original:**
<img width="760" alt="original" src="https://user-images.githubusercontent.com/13793769/36541383-01dc5006-17de-11e8-8764-544f5bb92f96.png">

Something must have gone wrong when submitting these files to this repository.

**Comment by jmsole** [comment]
I was looking into the sources yesterday and found this issue. Turns out the folders have been zipped but the UFO extension was kept. That explains the file size difference and not being able to open the UFOs in font-editing software. If you treat them as a compressed files and unzip them, UFOs work fine. Hope this helps!

**Comment by seejamescode** [comment]
@jmsole is right, this happens as soon as we zip the directory. It even happens when I download the files from Box. `.ufo` files are really folders that have added the `.ufo` extension. I think the only action we can take here is adding a content to the readme since GitHub downloads are always zipped up:

## Viewing source files

When you download zipped folders from this project and unzip them, you may notice the `.ufo` files can’t be opened. This is due those files being zipped also. To open the file, replace the `.ufo` file extension with `.zip`, unzip it, and then add back the `.ufo` file extension.

**Comment by BoldMonday** [comment]
@seejamescode That does not sound as an elegant solution tbh, especially since other repositories that host UFO files do not have this issue.

Have a look here for example:
https://github.com/adobe-fonts/source-sans-pro/releases
https://github.com/mozilla/zilla-slab/releases

**Comment by seejamescode** [comment]
I just did another test where I zipped it on my computer and then unzipped it. It worked! So, it is only Box’s zipping that messes us up.

**Comment by seejamescode** [comment]
Yeah, I just have to take the time to download each UFO file individually from Box.

I’ll send you back a zip that you can use for future development. Then it would be helpful to have any updates emailed to me instead of using the Box folder.
