### ISSUE TITLE
EOT files are missing from release

### ISSUE THREAD

**Issue by BoldMonday** [IBM/plex#137]
**Web.zip** from v1.0.0 release is missing all EOT files from the repository.

**Comment by seejamescode** [comment]
We didn’t include EOT files in our web release and css due to it being an outdated file type for web. If somebody has a use case for them, they can grab them from the source files zip. Check out the browser support for [EOT](https://caniuse.com/#feat=eot) and [WOFF](https://caniuse.com/#feat=woff) for more details.
