### ISSUE TITLE
Scripts to merge or separate

### ISSUE THREAD

**Issue by davelab6** [IBM/plex#149]
It seems to me that Latin, Greek, Cyrillic and Hebrew can be easily integrated into a single merged font family, but other scripts with different vertical metric requirements (Arabic, Devanagari, Thai) may need to be separate families. What is the current plan for that?

These might not include most or even any Latin characters, because a sophisticated text system will allow several fonts to be set up in a fallback stack. However, there are many simple text systems out there, where having an integrated Latin is desirable. If they are separate families, will they include Latin? Currently I believe an inline Latin is required by Google Fonts for this reason (because we want fonts to be a 'no brainer' even for less sophisticated users.) 

If they are separate families, what will they be named? They might reasonably be called eg "IBM Plex Sans Arabic", but to date Google Fonts has preferred to keep script/language names out of family names (eg Baloo has support for 10 scripts, but each has a name related to its primary language rather than the language/script itself: https://fonts.google.com/?query=baloo.)  The reason for this is that its possible to call the family without a subset declared, and in this case only basic Latin is returned.

**Comment by davelab6** [comment]
Yes, I agree that the vertical metrics is a fair reason to split things.

Could you use the Google Fonts Latin Core? This is bascially Latin 1 and a
few other things, 220 glyphs or so.
https://github.com/googlefonts/tools/blob/master/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam

I'll review the issue of using script names in the family names with the GF
team.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!

**Comment by ConradSchmidt** [comment]
Hi,

I'm working for Watson Knowledge Catalog and we're facing the issue that PDF generation produces missing characters form some languages (its actually a problem reported by customers, therefore we have a high priority on this). Problem is that these PDFs can have mixed content, because of language settings. So if we don't know which languages the PDF could contain, the font-type can't be provided individually. I saw that you separated the types, because of font-metrics (I'm not a font expert, so I'm not 100% what that means). In order to guarantee readable PDF a merged font (of all languages) would be a good fallback. I merged them myself to check if this is possible:
IBM internal repo: https://github.ibm.com/conrad-schmidt/ibm-plex-merged

Is this something you could provide, with a warning that this should be only used for special purposes (maybe not including it in the release zip, to prevent easy access to this font)?

Thanks!

**Comment by ConradSchmidt** [comment]
@vpicone should I open a new issue or is this repository no longer maintained?
