### ISSUE TITLE
language

### ISSUE THREAD

**Issue by psgraphics111** [IBM/plex#152]
There are over 100 languages and Yoruba ain't included, it is a language spoken by almost 30 million people worldwide, the BBC delivers news in Yoruba so i think IBM will do well to include Yoruba in the selection of languages for the font.

**Comment by BoldMonday** [comment]
Interesting! Do you have more information which letters in IBM Plex are missing to write Yoruba?

The fact that a certain language has not been listed does not automatically mean that the fonts lack the glyphs to write that language.

**Comment by psgraphics111** [comment]
The digraph Gb and gb are missing from the glyphs

**Comment by moyogo** [comment]
@psgraphics111 The digraph Gb and gb are typically compose of the letters G + b and g + b just like you typed. There is usually no need for single glyphs for these.

@BoldMonday The characters necessary for Yoruba are "a b d e f g h i j k l m n o p r s t u w y à á è é ì í ò ó ù ú ṣ ẹ ọ gb ẹ̀ ẹ́ ọ̀ ọ́" (and uppercase) out of which "ẹ̀ ẹ́ ọ̀ ọ́" are composed with base letters and combining marks. IBM Plex fonts do not have the mark feature necessary for the positioning of those combining marks.

**Comment by BoldMonday** [comment]
@moyogo Not sure what you mean. IBM Plex fonts downloadable from this repository (with the exception of the split webfonts) do have a mark feature. I haven’t tested the glyphs in question, but there is a good chance it already works.

**Comment by moyogo** [comment]
@BoldMonday There is no mark feature for "ẹ ọ", which are needed for "ẹ̀ ẹ́ ọ̀ ọ́".

**Comment by BoldMonday** [comment]
@moyogo This is something I still find difficult to get a grasp on with multiple combining marks. What is the correct approach for the glyphs in question:
- only mark feature for combining grave and acute accents to "ẹ ọ"
- or also a mark feature for combining dot below to "é è ó ò"
?

**Comment by psgraphics111** [comment]
@moyogo thats the problem, i feel like it shouldn't be composed of two different letters, i have just completed a university project (yoruba typeface) where i created the Gb  & gb as a standalone glyph in it's own right, complete with the letters (A-Y) and lowercase.

@BoldMonday there is still a bit of confusion as to exactly if the (e and o) should have an acute or grave accent and if they should have a dot below, i was thought how to write yoruba with the acute accents on the e(pronounced er) and o (pronounced or), there was no dot below for any character, based on the research i have done, there is no set way of how the accents and combining marks are to be used, spoke to my tutor regarding this and apparently there are groups of people that needs to come together to decide exactly how this things work and they all have to agree to it.

**Comment by moyogo** [comment]
@psgraphics111 Interesting! Where is your tutor from?

> apparently there are groups of people that needs to come together to decide exactly how this things work and they all have to agree to it.

There are several vernacular orthographies which do indeed differ quite a lot, not just for Yoruba. The é and ó or è and ò are commonly used in vernacular orthographies of many African languages.
However there are two well defined official Yoruba orthographies, one that has been used in Nigeria for a very long time and a different one in Benin. Both use the accents for optional tone marking, they differ in how they reprensent [ɛ], [ɔ] (your "er" and "or") and [ʃ] ("sh" as in "she"), by either ẹ ọ ṣ in Nigeria or ɛ ɔ sh in Benin.

The National Language Centre has published orthography manuals for several Nigerian languages since the 1980s. See Ayo Bamgbose (1982), *Orthographies of Nigerian languages: manual I*, Lagos, Federal Ministry of Education, National Language Centre, for the Yoruba orthography.
The orthography is widely used (with some variation, including in optional tone marking), and since before the publication of the manuals, see for example the newspapers [*Alaroye*](https://www.google.com/search?tbm=isch&q=%22Alaroye%22&tbs=imgo:1) or [*Iroyin Wurọ*](https://www.google.co.uk/search?tbm=isch&q=%22Iroyin+Wuro%22&tbs=imgo:1), or also [Yoruba Wikipedia](https://yo.wikipedia.org), [BBC Yoruba](https://www.bbc.com/yorùbá) which all use ẹ ọ and some which do so with tone marks.

In Benin, the Centre national de linguistique appliquée (CENALA) has published and revised the *Alphabet des langues nationales*, since 1975. The latest editions I have been able to check include an alphabet for Yoruba. I don’t know to which extent that orthography is used but it is official so it cannot be ignored.

**Comment by moyogo** [comment]
@BoldMonday Shapers will usually normalize eacute + dotbelowcomb to edotbelow + acutecomb, but I’d recommend having anchors on both eacute and edotbelow.

**Comment by BoldMonday** [comment]
Thank you @moyogo for the detailed feedback! We will add this to our to-do list for a next release.

**Comment by psgraphics111** [comment]
@moyogo i'm not exactly sure why where my tutor is from is relevant to what he told me. It's obvious you know what you are talking about but the reality is you don't get taught how to write yoruba like that, i got told only some vowels have acute accents (e and o) now this was almost 15 years ago, whilst doing research for my project i called my cousin back in Nigeria and unfortunately the same thing is still going on, they are still getting told only certain vowels have accents, they don't  get taught about letters having anchors on eactue and edotbelow, so unless all the teachers are just uneducated then there is a fundamental problem with how exactly yoruba needs to be written.

**Comment by moyogo** [comment]
@psgraphics111 I was curious to know if your tutor was from Nigeria or Benin since both countries have different Yoruba orthography traditions. I was pointing out that Nigeria Yoruba’s standard spelling has long been used in literature and media. I don’t doubt that people may not use the standard spelling for a variety of reasons (including disconnect between standard orthography, what people are or were taught in some schools, what people end up using).

For the anchors, that is only specific to font design.
