### ISSUE TITLE
Npm Module doesn't provide IBM Plex Sans Medium

### ISSUE THREAD

**Issue by leandro-cassa** [IBM/plex#166]
I don't know if there is a specific reason why your npm module
https://www.npmjs.com/package/@ibm/type

Doesn't provide IBM Plex Sans Medium, but it would definitely help me with my project.

**Comment by seejamescode** [comment]
Hi @leandro-cassa,

`@ibm/type` is frozen right now, but will eventually (v1.0.0) have all of IBM’s latest typographical choices for our own experiences. Because it is opinionated, it will only have the weights IBM wants to use for digital experiences. Medium is not one of those.

Please use `@ibm/plex` for access to all weights and the latest versions of them (at the moment).
