### ISSUE TITLE
May be intentional but "f" and "i" run together

### ISSUE THREAD

**Issue by KelseyJDuke** [IBM/plex#172]
In Plex Sans (all weights) the arm of the "f" runs into the "i". Noticing that changing the character spacing doesn't make a difference, so it might just be a characteristic of the typeface...wanted to check in here for more info!

**Comment by SmiVan** [comment]
I'm fairly certain it's an intentional ligature.

**Comment by mgrhm** [comment]
It's definitely intentional.  It's [a typographic ligature](https://en.wikipedia.org/wiki/Typographic_ligature), designed to increase legibility by removing parts of the letterforms that may otherwise 'collide'.  'fi', 'ff', and 'fl' are the most common ones in English.

Plex Sans's implementation is quite usual.  It retains the tittle on the 'i', where normally that would be omitted and the terminal 'f' would extend over the space above the 'i'.

**Comment by KelseyJDuke** [comment]
gotcha, thanks for the explanation!
