### ISSUE TITLE
Add support for (modern) Greek.

### ISSUE THREAD

**Issue by cosmix** [IBM/plex#179]
Since support for Cyrillic is already there, it only takes a bit more effort to add support for modern Greek.

**Comment by inferno986return** [comment]
I too want to see Greek support for Plex as I often use it as the UI font on Chrome. Surely IBM has Greek customers and would benefit from the whole type family supporting Greek?

**Comment by BoldMonday** [comment]
Monotonic Greek for IBM Plex Sans has been delivered by us end of May, and is currently in the hands of the IBM engineers who have write access to this repo. Not sure why it is taking so long.

Other parts of the family (Mono, Serif, Sans Condensed) will follow later. For one, we would love to add polytonic Greek to IBM Plex Serif. However, currently the expansion for Asian scripts has a higher priority.

**Comment by mjabbink** [comment]
First time I’m hearing about wanting to do polytonic. It could have easily been included in Greek budgeting. Now it will have to wait until Neil 2020.

**Comment by cosmix** [comment]
@BoldMonday Thanks for getting back to me. I understand the interest in Greek is relatively marginal, at least compared to other scripts, given the relatively low number of people actually using it.

Yet I'm surprised you mentioned Polytonic Greek; Polytonic is only interesting to scholars, who may number in the high tens of thousands globally, while monotonic Greek support is essential for all of the greek speaking population throughout the globe (probably around 20M people), as well as (in the case of your monospaced font) engineers creating software.

I'm quite certain you have a number of criteria when determining your priorities and I appreciate the heads up, but I'm somewhat confused by your roadmap. Why did you choose Sans as the first (and currently only) face getting Monotonic Greek? Since you already have Roman and Cyrillic in place, adding Monotonic Greek support throughout the family is a relatively minor undertaking, especially compared to that of creating Asian Scripts. If you could provide a tentative roadmap for the addition of Monotonic Greek in Mono I would very much appreciate it.

Thanks!

**Comment by BoldMonday** [comment]
@cosmix I cannot comment more on the roadmap than what is already there. But I think a couple of points need clarification:

1. When I mentioned polytonic Greek for IBM Plex Serif I meant that mainly because I think a serif style with modulated stroke widths lends itself best for polytonic. It certainly would make most sense. Perhaps polytonic could be added to Sans or Mono too in the future – but that decision is not made by me alone.

2. Other scripts where expansions have been made for recently (Hebrew, Thai, Arabic, Devanagari) are also only done in one style (usually IBM Plex Sans). In that sense Greek is not treated any differently.

3. When adding a script to one of the subfamilies we go into great lengths to explore what is the best solution for each of those subfamilies. For example, if you compare the Cyrillic shapes in Sans versus Serif versus Mono you will notice big differences sometimes in construction. For every script we set ourselves those same goals. Now, added to the fact that every subfamily has eight weights in roman and italic, I hope it is clear that *any* Greek expansion is not a trivial task and involves multiple months of work together with an accompanying budget.

**Comment by cosmix** [comment]
@BoldMonday 

Re:

1. I agree, but my point wasn’t about Serif or not. It was about the mention of Polytonic Greek. In my humble opinion, I wouldn’t bother with Polytonic Greek until well after Monotonic Greek was done and dusted, as very few people care about Polytonic nowadays.

2. That’s clear. Thank you. The question, however, was not whether Greek is treated differently to other languages, but _why Sans is_.

3. It’s clear that you are doing your job properly and taking the time to carefully design the glyphs for the scripts you’re working on. I never doubted for a second the amount of work it takes. Again, however, you misinterpreted my point, which is the following: The Modern Greek alphabet shares many glyphs with its Roman and Cyrillic counterparts (Cyrillic was derived from Greek after all). Most font faces share several glyphs across scripts as they are identical. Capital Alpha and A, Beta and B, Epsilon and E, Gamma and (Cyrillic) Ghe, Pi and (Cyrillic) Pe and so on. And you have _already done the hard work_ (for all weights, and all family members of Plex for both Roman and Cyrillic). So I was not questioning (or even insinuating anything regarding) the amount of work it takes to design glyphs for different styles and weights in a new script. I was, quite clearly I hope, making the point that since you have already added Roman and Cyrillic support in Plex, adding Monotonic Greek is not equivalent to the amount of work needed in order to add support for a completely new script, but much much less.

In any case, I very much appreciate both your work and your exceptionally fast response to my queries. I will keep checking this repo for any updates that include Greek in the future.

Thanks again.

**Comment by mjabbink** [comment]
But to your point it can easily become the next serif script but we prioritize around number of users (so Greek serif or Arabic or Hebrew for high contrast versions) and whether to add Bengali and Tamil.

**Comment by cosmix** [comment]
Thanks, @mjabbink — that clarifies things somewhat. Note that I don't (personally) particularly care about (nor did I focus specifically on) Plex Serif; Plex Mono with Greek support is what I'm mostly interested in. :)
