### ISSUE TITLE
Add Apache license into all font folders (This will live as a dual license with the OFL)

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#190]
[LICENSE-Apache.txt](https://github.com/IBM/plex/files/2274564/LICENSE-Apache.txt)

**Comment by inferno986return** [comment]
So this means the entire family is officially dual-licensed with Apache? Cool, I'll update the Wikipedia page. :-)

**Comment by mjabbink** [comment]
yes, dual license.

**Comment by mjabbink** [comment]
yes, dual licensed.
 
 
 
Mike Abbink
—
Executive Creative Director,
IBM Brand Experience & Design
+1 917 291 7516
E-mail: mjabbink@us.ibm.com
 
 
 
 
----- Original message -----From: Hal Motley <notifications@github.com>To: IBM/plex <plex@noreply.github.com>Cc: Mike Abbink <mjabbink@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/plex] Add Apache license into all font folders (This will live as a dual license with the OFL) (#190)Date: Thu, Aug 9, 2018 11:37 AM 
So this means the entire family is officially dual-licensed with Apache? Cool, I'll update the Wikipedia page. :-)

**Comment by BoldMonday** [comment]
I think many font folders are currently missing [license.txt](https://github.com/IBM/plex/blob/master/LICENSE.txt) with OFL license as well.

**Comment by mjabbink** [comment]
That license should probably be renamed to —>  OFL_license.txt  and the other to—>  Apache_license.txt
 
 
Mike Abbink
—
Executive Creative Director,
IBM Brand Experience & Design
+1 917 291 7516
E-mail: mjabbink@us.ibm.com
 
 
 
 
----- Original message -----From: Paul van der Laan <notifications@github.com>To: IBM/plex <plex@noreply.github.com>Cc: Mike Abbink <mjabbink@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/plex] Add Apache license into all font folders (This will live as a dual license with the OFL) (#190)Date: Fri, Aug 10, 2018 8:49 AM 
I think many font folders are currently missing license.txt with OFL license as well.

**Comment by twardoch** [comment]
Github relies on the fact that there is one `LICENSE` or `LICENSE.txt` file in the main folder of the repository. This allows Github to "detect" the license. Then, an extra badge appears in the Github UI, and the repo to be found when users are looking for repos licensed under the specific license: 

- https://help.github.com/articles/adding-a-license-to-a-repository/
- https://help.github.com/articles/licensing-a-repository/

Since Apache 2 is a more liberal license that can be applied to any software, not just fonts, I recommend the following: 

1. Add `LICENSE.txt` that contains the Apache 2.0 license. This should be the “default” license because this way, the scripts and other files in the repo will also be automatically licensed under the Apache 2.0 license (the OFL license can only be applied to fonts)
2. Add `LICENSE-OFL.txt` that contains the OFL license. 
3. Add the following verbiage to the README: 

```
All files in this repository, including the source and final font files, are licensed under the [Apache License, Version 2.0](./LICENSE.txt). In addition, the source and final font files are also licensed under the [SIL Open Font License, Version 1.1 (OFL)](./LICENSE-OFL.txt) with Reserved Font Name "Plex". You can select which license terms you wish to use, modify and/or further distribute the fonts under. 
```

**Comment by davelab6** [comment]
I have no objections to this, although the Apache license is unsuitable for
fonts.

**Comment by alisonjoseph** [comment]
FYI I will be removing the apache license today as requested from IBM legal

**Comment by BoldMonday** [comment]
@alisonjoseph Any explanation why?

**Comment by alisonjoseph** [comment]
"There are issues we need to discuss if we keep want to have IBM Plex under Apache
IBM Plex hasn’t been authorized for Apache usage yet."

**Comment by mjabbink** [comment]
I think there is confusion that the Apache license is for Plex itself which is not the intent. The font is OFL and to include the OFL font in other offerings we needed the Apache. This was my understanding from some other legal folks. I reckon it turns out that is not the case and we need to modify how that is communicated.
 
M
 
 
Mike Abbink
—
Executive Creative Director,
IBM Brand Experience & Design
+1 917 291 7516
E-mail: mjabbink@us.ibm.com
 
 
 
 
----- Original message -----From: Alison Joseph <notifications@github.com>To: IBM/plex <plex@noreply.github.com>Cc: Mike Abbink <mjabbink@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/plex] Add Apache license into all font folders (This will live as a dual license with the OFL) (#190)Date: Tue, Aug 21, 2018 10:43 AM 
"There are issues we need to discuss if we keep want to have IBM Plex under ApacheIBM Plex hasn’t been authorized for Apache usage yet."

**Comment by davelab6** [comment]
> FYI I will be removing the apache license today as requested from IBM legal

Good news! I am very happy to hear this, because I think including anything alongside OFL makes the licensing situation more complex than it should be, which is a big deal in and of itself. 

The Apache license is unsuitable for fonts, because when fonts are embedded integrally in documents (like PDFs) under Apache, the Apache terms don't have any special terms for this special kind of redistribution, and according to one's interpretation of the license/situation, one may need to include a copy of the whole Apache license with the document (which sucks.) The OFL has explicit handling of such document embedding. 

Additionally, the OFL says that recipients can not redistribute under "any other license," which could be interpreted to mean that anyone getting a copy of IBM Plex under both licenses can only ever redistribute under the OFL anyway.

**Comment by mjabbink** [comment]
There were some misunderstandings on legal regarding the OFL. IT has been resolved and are back to the original way we did it. Just OFL.
 
M
 
 
Mike Abbink
—
Executive Creative Director,
IBM Brand Experience & Design
+1 917 291 7516
E-mail: mjabbink@us.ibm.com
 
 
 
 
----- Original message -----From: Dave Crossland <notifications@github.com>To: IBM/plex <plex@noreply.github.com>Cc: Mike Abbink <mjabbink@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/plex] Add Apache license into all font folders (This will live as a dual license with the OFL) (#190)Date: Thu, Aug 23, 2018 10:28 AM 
FYI I will be removing the apache license today as requested from IBM legal
Good news! I am very happy to hear this, because I think including anything alongside OFL makes the licensing situation more complex than it should be, which is a big deal in and of itself.
The Apache license is unsuitable for fonts, because when fonts are embedded integrally in documents (like PDFs) under Apache, the Apache terms don't have any special terms for this special kind of redistribution, and according to one's interpretation of the license/situation, one may need to include a copy of the whole Apache license with the document (which sucks.) The OFL has explicit handling of such document embedding.
Additionally, the OFL says that recipients can not redistribute under "any other license," which could be interpreted to mean that anyone getting a copy of IBM Plex under both licenses can only ever redistribute under the OFL anyway.

**Comment by inferno986return** [comment]
I'm admittedly still rather confused by this debacle, but I have made an attempt to summarise the situation in the Wikipedia article with a link back to this thread.

**Comment by davelab6** [comment]
> I have made an attempt to summarise the situation in the Wikipedia article with a link back to this thread

I'm not sure this is worth noting in the Wikipedia article; it is not important at all :)

**Comment by mjabbink** [comment]
Definitely not worth mentioning ever again or  anywhere else as it’s now completely irrelevant and was simply something that should never even have happened. Giving anymore attention is even more confusing and a waste of time. 

—
Mike Abbink
Executive Creative Director, 
IBM Brand Experience & Design 
IBM Distinguished Designer

+1 917 291 7516 mobile
mjabbink@us.ibm.com
mike@mikeabbink.com

—
Sent via iPhone
