### ISSUE TITLE
FontLab Studio 5 / Robofab end of life

### ISSUE THREAD

**Issue by mbutterick** [IBM/plex#206]
“To build binary font files from vfb sources you need FontLab Studio 5. A Python script called IBM Plex export FDK files.py is necessary to export the proper files from FontLab. In order to run this script you will need the RoboFab library.”

Robofab [development has ended](https://groups.google.com/d/msg/robofab/QfjZCFpiQZA/W9l90SnjAgAJ). The new Mac OS Mojave is the last release that will support FontLab Studio 5 ([because it’s 32-bit](https://9to5mac.com/2018/06/05/macos-mojave-32-bit-support/)). 

What plans, if any, exist to transition the `plex` sources onto tools that are not reaching EOL?

**Comment by BoldMonday** [comment]
Hi @mbutterick,

The repository also includes UFO files from the master weights. They can be opened in several font editors.

We would like to transition to a situation where all source files are truly in an open format such as UFO, but hinting is still the main bottleneck here. At the moment there are no open source hinting tools besides autohinters.

Perhaps the best solution will be to supply both unhinted source files in UFO format, and hinted source files in another format.

I’m curious what other people think.

**Comment by davelab6** [comment]
If you switch the preferred form of modification to quadratic outline UFO,
compile with fontmake, and hand hint with ttfautohint controls files,
you'll have a fully libre build chain.

If you stay with cubic outlines, then as the cu2qu algorithm changes it
will invalidate the ttfautohint controls files, as the point numbers/orders
change. So you'll need to effectively redo it for every release.

You could also use the vtt autohinter plus it's equivalent of control
files, on each important binary release, and also redo it for each release.
With the liberation of vtt on the horizon, this may be become a fully libre
workflow.

The dama workflow is entirely UFO based and I think handles hinting, I
wonder if anyone there may care to comment.

**Comment by BoldMonday** [comment]
@davelab6 Not too big a fan of ttfautohint tbh. I prefer a solution where we can maintain the current level of hinting.

Yes, a VTT compiler would be very helpful. Although I don't know how far that horizon still is.

**Comment by moyogo** [comment]
For the Dalton Maag workflow, we store the VTT hinting in the UFO data folder. It is generated in VTT, roundtripped between the UFO and the VTT TTF with [vttLib](https://github.com/daltonmaag/vttLib).

Since May, the [UFO3 spec allows for PS hints](https://github.com/unified-font-object/ufo-spec/pull/53) to be stored in the UFO in a standard way. The fontmake toolchain does not handle that yet.
There are non-standard ways to store the low-level TT instructions (we use VTT instructions but some private tools use fontTools TTX instructions) and there has been some discussion to store a higher-level TT hints (see unified-font-object/ufo-spec#43).

If I understand correctly, you do PS and TT hinting from the PS hints in FontLab.
Storing the PS hints in the UFO can now be done and it shouldn’t be much work to implement compiling it in the font with fontmake.
For the TT hinting to TT instructions, one would have to compile the PS hints into TT instructions. There are a couple of private tools that do this. Adobe might be interested in having a public one.
@miguelsousa Could you comment?

**Comment by mbutterick** [comment]
BTW my question isn’t about UFO or open formats. I’m asking if the build environment is going to change to use currently supported tools, and if so, when. I assume this is inevitable for the continuing development of `plex` because, for instance, FLS5 will not even be runnable on Mac OS a year from now.

**Comment by BoldMonday** [comment]
The build environment is going to change when viable alternatives are available. And as you can see from this discussion, there are not many options yet.

**Comment by davelab6** [comment]
@BoldMonday said,

> Not too big a fan of ttfautohint tbh. I prefer a solution where we can maintain the current level of hinting.

What does the current level of hinting involve, that ttfautohint controls files does not offer?

@mbutterick said,

> I’m asking if the build environment is going to change to use currently supported tools

Its a fair question, but, which tools do you have in mind?

@moyogo said,

> I’m asking if the build environment is going to change to use currently supported tools ... There are a couple of private tools that do [compile the PS hints into TT instructions.]

**Comment by twardoch** [comment]
FontLab Studio 5 is, indeed, at end-of-life. But the FLS5 TrueType hinting engine is part of FontLab VI, of course. 

Version 6.1, due out in a few days, adds native for traditional components, including nested components, so FLVI will no longer change the “source glyph” of a component in some cases, as was the case with 6.0. 6.1 also improves UFO 3 handling a bit more. 

Given how much FontLab VI has progressed in the last 9 months since the initial release, I’m pretty sure that in a year from now, FontLab Studio 5 for Mac will definitely and deservedly be obsolete, though of course the Windows version will continue to run on Windows, and on the Mac via Wine. 

But I agree that sticking to the old platform is not a good idea. At FontLab, we’ll be happy to help transition Plex sources into a more modern workflow. 

I’m a big fan of Plex myself, and we’re actually using the family within our communication (e.g. on http://forum.fontlab.com/ ). 

If you need anything specific, please let us/me know!

**Comment by madig** [comment]
> If you stay with cubic outlines, then as the cu2qu algorithm changes it will invalidate the ttfautohint controls files, as the point numbers/orders change. So you'll need to effectively redo it for every release.

I'm still sitting on some code that can transfer VTT (TSI3 only atm) code to new outlines that ideally have matching on-curve points. We use it to transfer hints when we go from cubic-and-quadratic sources to cubics-only. If there is interest, I can dump it on GitHub... Want to integrate it into vttLib at some point but went down on the priority list.

**Comment by jenskutilek** [comment]
> On the other hand, if FontLab would open source the TTH compiler that would help as well.

I have my own Python implementation of a FontLab-style TTH compiler which can take an UFO (from vfb2ufo so it contains the FL TT hinting code) and compile the TT instructions. I would be open to release it if there are no objections from the FontLab guys.

**Comment by BoldMonday** [comment]
That sounds great @jenskutilek.

How does your implementation deal with deltas applied to alignment zones?
AFAIK these instructions cannot be accessed with the FL scripting API.

**Comment by jenskutilek** [comment]
The alignment zone deltas are stored in the UFO generated by vfb2ufo, so they can be accessed there by any script working with the UFO.

**Comment by rimas-kudelis** [comment]
@jenskutilek, have you released that compiler you  were talking about?
