### ISSUE TITLE
The "3" AND "B" look wrong but not always...

### ISSUE THREAD

**Issue by fthx** [IBM/plex#214]
[Ubuntu 18.10 GNOME, Plex 1.2.1, size 11 tested]

WxMaxima : 
![image](https://user-images.githubusercontent.com/23138504/49180573-547c4480-f355-11e8-9766-4f7e88157495.png)
LibreOffice : 
![image](https://user-images.githubusercontent.com/23138504/49180600-66f67e00-f355-11e8-9294-31c9c4bb69e5.png)
Firefox 63 : 
![image](https://user-images.githubusercontent.com/23138504/49180690-ae7d0a00-f355-11e8-8b1a-c289712c55c1.png)
the same in size 12 instead of 11 : 
![image](https://user-images.githubusercontent.com/23138504/49180855-2c411580-f356-11e8-8afa-813ce9915883.png)
GNOME Control Center : 
![image](https://user-images.githubusercontent.com/23138504/49180779-f0a64b80-f355-11e8-8fcf-9698a5eed7e1.png)

**Comment by mjabbink** [comment]
yikes!

**Comment by BoldMonday** [comment]
Check the font rendering settings and make sure that the system is using the hinting from the font itself.

Also check which font format is installed. TrueType (ttf) or OpenType (otf) may render differently.

**Comment by fthx** [comment]
The Debian package use OTF, as I did when I was using directly the fonts from this repo.
Well, I got it : 
![image](https://user-images.githubusercontent.com/23138504/49209601-39442000-f3bb-11e8-902d-1d16e8fd7f31.png)
If I choose any other optimisation (light = Ubuntu & GNOME default, etc.), the 3 and the B (and others) are looking bad.
But with no optimisation (anti-aliasing) you can see that the fonts are blurry : 
![image](https://user-images.githubusercontent.com/23138504/49209794-bcfe0c80-f3bb-11e8-99b6-0d251c8103e5.png)

So, from a concrete POV, I did not succeed to render Plex in a good shape.

**Comment by BoldMonday** [comment]
OTF fonts cannot be optimised specifically for low resolution screen environments.
So in this case the rounding of pixels on the grid is out of our control unfortunately.

The rendering might look better with the TTF versions.

**Comment by fthx** [comment]
Ok, I downloaded TTF from GitHub.

So I hacked around and the better result is given by these settings in Tweaks : 
![image](https://user-images.githubusercontent.com/23138504/49214848-c8573500-f3c7-11e8-99c4-c38e913cd875.png)

These settings give bad 3 and B with OTF.

**Comment by fthx** [comment]
Running latest 1.2.3 ttf from this repo, I feel the rendering to be better, not blurry at all : 
![image](https://user-images.githubusercontent.com/23138504/50568439-1a3a0480-0d52-11e9-8601-267b72a3132d.png)
Or maybe it's just the 31. december's wine...

**Comment by fthx** [comment]
Plex 1.2.3 from this site, TTF version, fonts settings unchanged.

So, today I noticed that the "3" rendering is bad running Synaptic in X but ok in Wayland (that I do use 99% of the time). Anther tricky behaviour, as I don't see it with the fonts I used (Ubuntu, Liberation2, Roboto).

**Comment by paride** [comment]
@fthx The OTF format for the Debian package has been chosen after comparing TTF and OTF in https://github.com/IBM/plex/issues/198.

In the comparisons OTF did render well enough on screen (modern screen are not so low in resolution) and offered some other (minor) advantages over TTF. The OTF samples in https://github.com/IBM/plex/issues/198#issuecomment-416683971 did render well even at low sizes, so I don't think the issue you observe is due to an inherent limitation of the format. I don't know what the problem could be and at this point I'm not happy with the idea of switching to TTF without a clear and strong reason...

**Comment by fthx** [comment]
I'm far from a fonts expert, but as an user I agree that there is an issue, whatever the cause is, and fore sure not Debian-packaging related since it happens too with a local install from this repo.

But I do not agree that all is ok with OTF, since : 
https://github.com/IBM/plex/issues/198#issuecomment-416683971
already showed the "3" issue in size 11 sans fonts.

**Comment by paride** [comment]
@fthx You are right. The autohinted version looks good (see image below from https://github.com/IBM/plex/issues/198#issuecomment-416683971), but I'm not sure if it is supposed to look better than the natively hinted one.  In https://github.com/IBM/plex/issues/214#issuecomment-442753003 you show that the unhinted version is blurry but does not show the issue for `3`. How is it that with hinting turned on we get a worse result? Could this be a hinting bug? @BoldMonday?

https://user-images.githubusercontent.com/20808761/44739134-f8d7bc00-aac4-11e8-82e8-2e2c54ddabf3.png

**Comment by paride** [comment]
This is how it renders on my system within LibreOffice, from size 2 to 9.
![2019-01-10-185349_135x43_scrot](https://user-images.githubusercontent.com/7614669/50987170-291a7700-1509-11e9-94f4-f288fe53d327.png)
The issue shows for the character `3` in size 3.

**Comment by BoldMonday** [comment]
@paride: I repeat: *OTF fonts cannot be optimised specifically for low resolution screen environments.*

There are no hinting instructions in PostScript to control specific rounding behaviour for specific point sizes. The fact that the autohinter gives a better result in this particular case does not mean it will render better in every other environment.

**Comment by paride** [comment]
I uploaded a new package revision to Debian, this one install the TTF fonts instead of the OTF.

**Comment by Sunspark-007** [comment]
Apologies for the late comment, but I agree with the decision to go with TTF here for the sans font. The difference is more noticeable if one is using dark mode rather than light mode. Easy to see with two screenshots and flipping between the two. The x-height on the TTF is taller which means the "e" and "a" letters don't get as crushed, etc. Another observable difference on light mode is that the letters are more "black" with the TTF version (albeit a touch more contrasty/spindly though which may or may not be more straining) compared to the OTF version which is slightly lower contrast/touch grayer.

This observation was made in KDE 5.26 with Firefox 113 on x.org. System set for a logical dpi of 144. The KDE system settings for hinting don't really apply here because both Chrome and Firefox flatpaks ignore system settings for the most part (i.e. they continue anti-aliasing, even if one turns it off in KDE) so this is observation is made with the browsers choosing for you what hinting you're going to be using.
