### ISSUE TITLE
Langauge unicodes 

### ISSUE THREAD

**Issue by sockol** [IBM/plex#219]
Need to have non-English fonts add unicode ranges so that we can have `IBM Plex` for all languages, not `IBM Plex Thai` to get the Thai fonts to work.
Or maybe this is intentional?
 
Edit:
Also, setting `font-family: IBM Plex Thai` or `IBM Plex Devanagari`  doesn't seem to work
@mjabbink @alisonjoseph

**Comment by dkuehn** [comment]
Hello,

I guess you catched the wrong Daniel here. I’m not aware of any Project where Thai Fonts play a role.

Greetings from Berlin,
Daniel

E-Mail daniel.kuehn@aperto.com
Phone +49 30 283921-705
Fax +49 30 283921-29

Aperto GmbH – An IBM Company
Chausseestraße 5, 10115 Berlin
http://www.aperto.com<http://www.aperto.de/>
http://www.facebook.com/aperto
https://www.instagram.com/aperto_agency
https://www.xing.com/companies/apertoag

HRB 181949 B, AG Berlin Charlottenburg
Geschäftsführung: Dirk Buddensiek (CEO), Kai Großmann, Stephan Haagen, Daniel Simon



Von: Semur Nabiev <notifications@github.com<mailto:notifications@github.com>>
Antworten an: IBM/plex <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Dienstag, 18. Dezember 2018 um 22:52
An: IBM/plex <plex@noreply.github.com<mailto:plex@noreply.github.com>>
Cc: "Kühn, Daniel" <Daniel.Kuehn@aperto.com<mailto:Daniel.Kuehn@aperto.com>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: [IBM/plex] Langauge unicodes (#219)


Need to have non-English fonts add unicode ranges so that we can have IBM Plex for all languages, not IBM Plex Thai to get the Thai fonts to work.
Or maybe this is intentional?

@dkuehn<https://github.com/dkuehn>
@robin-cannon

**Comment by BoldMonday** [comment]
@sockol This is intentional.

**Comment by twardoch** [comment]
Fonts that mix different scripts don’t work well, technically. There are many technical limitations such as maximal sizes of OpenType layout tables, hinting, various linespacings and other that make it really hard to make fonts that span multiple scripts without compromises. Fonts that are made per-script work better. 

The exception is “simple” alphabetic scripts like Latin, Cyrillic, Greek, Armenian, Georgian, Glagolitic, IPA etc. — those can be pleced into one font. 

This is how Microsoft and Apple do system fonts, this is how Google develops the Noto project, and I think it's right that Plex goes the same way. 

Also, the modular approach makes it much easier to split the work between teams and coordinate timing.
