### ISSUE TITLE
Generating Fontlab Sources from UFO

### ISSUE THREAD

**Issue by weiweihuanghuang** [IBM/plex#228]
I'm trying to generate instances from the UFO masters but it looks like you have Fontlab instances, may I ask how you generated the Fontlab instances?

I'm working with the IBM Plex Mono .UFOs but I think it probably applies across the board. What are the differences between the postscript and truetype Fontlab files?

**Comment by BoldMonday** [comment]
The IBM Plex instances started their life as interpolated files which were checked and refined manually for rounding errors in outlines and metrics. Afterwards they were converted to TrueType outlines, and together with the PostScript versions they were hinted in FontLab 5.

If you are interested to work with the instances then I strongly recommend to take the FontLab files because these are of a much higher fidelity than plain interpolated instances.

With a utility such as `vfb2ufo` these files can be converted to UFO files. Although you will probably loose most, if not all all, hinting data when doing so.

**Comment by weiweihuanghuang** [comment]
I see, thanks for the explanation!

**Comment by weiweihuanghuang** [comment]
Looks like many of the mono glyphs are no longer compatible for interpolation by the way

**Comment by BoldMonday** [comment]
That is possible. The instances are the final files.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
