### ISSUE TITLE
Italicizing text

### ISSUE THREAD

**Issue by adamcc** [IBM/plex#255]
Using the Plex Sans Text weight in Pages: when italicized, the text converts to Medium Italic instead of Text Italic. De-italicizing converts it to Medium (roman).

**Comment by BoldMonday** [comment]
Thank you for the report! We will investigate what is the cause of this behaviour and whether it can be remedied in the fonts themselves.

**Comment by adamcc** [comment]
@BoldMonday 
Thanks for designing Plex, it's really great!

1.     In what version of MacOS does this behaviour occur?
10.14.5

2.     In what version of Pages does this behaviour occur?
8.0

3.     From what source did you download/install the IBM Plex fonts?
Github

4.     What version of Plex Sans Text are you using? This information can be retrieved in Font Book from the menu View > Show Font Info
Version 3.1

**Comment by mjabbink** [comment]
@adamcc you’re welcome! Happy to hear you like it.

**Comment by mjabbink** [comment]
@BoldMonday is this resolved?

**Comment by BoldMonday** [comment]
We can replicate the issue here but are unable to establish what is causing it. The information in the fonts is consistent and following the official specs.

We’ve checked some other families using the name **Text** as weight indicator (e.g. Milo Pro) and they exhibit the same misbehaviour. Based on the latter I’m inclined to believe that Pages has a problem with style-linking when a typeface family contains a weight named Text.
