### ISSUE TITLE
Cannot choose Mono Italic

### ISSUE THREAD

**Issue by sutibu** [IBM/plex#288]
Thank you for these absolutely wonderful fonts.  I enjoy the design decisions chosen.

I stumbled on a possible issue, when Mono regular & Mono italic are installed...

Some programs will not let you chose the italic style.

    Chrome (78.0.3904.) on MacOS (10.14).  Settings... Customize font, one only sees Regular.
    Putty on Windows 10.  (free ssh client).  If both styles are installed, one only sees Regular.

While other programs work.
    
    MS Word, one can choose Mono Regular or Mono Italic styles for text.

Is this a known issue?  Is there a fix coming or a work around?

**Comment by BoldMonday** [comment]
All italic styles in IBM Plex are "style-linked" to their roman counterparts.
This means that in order to use them in certain environments one needs to choose the roman font and then apply <italic> as style. For example in css this can be done by using `font-style: italic;` property.

Related: https://www.adobe.com/support/techdocs/328508.html

**Comment by sutibu** [comment]
Paul, BoldMonday, thank you for the quick response & link to the Adobe article.  Now I know a little more about how things work.

Let me try a test on another computer & will update this issue with my findings.
