### ISSUE TITLE
Wrong vertical size using bold fonts size 11

### ISSUE THREAD

**Issue by fthx** [IBM/plex#291]
Hi,

Running Ubuntu 20.04 dev, GNOME, IBM Plex from official Debian/Ubuntu repository, v. 4.0.2, TTF, size 11, IBM Plex Sans.

Running Thunderbird : 
![image](https://user-images.githubusercontent.com/23138504/70940069-da932800-2049-11ea-922a-56455612e744.png)
I noticed the same bug running Geary mail app.

Same in LibreOffice, size 11 too : 
![image](https://user-images.githubusercontent.com/23138504/70940228-2ba31c00-204a-11ea-9fb4-29b7d37e346c.png)

But oddly in size 12 e.g. there is no issue : 
![image](https://user-images.githubusercontent.com/23138504/70940297-4d040800-204a-11ea-8bb3-4c97a1284fb9.png)

**Comment by BoldMonday** [comment]
Based on some tests that we did this appears to be a rendering error caused by the rasterizer in Linux.

Firstly we checked the vertical dimensions for uppercase letters in all styles of IBM Plex Sans. They are exactly the same -- the cap height is 698 units in all fonts. This means that the bad rendering cannot be caused by a difference in vertical dimensions.

We did an extensive comparison of sizes for all fonts on Windows. This was our target platform when hinting the TrueType fonts. Here it is clear that there is no jumping in cap height between the different styles in a particular size.
![IBM_Plex_Sans-TTF-waterfall-Windows-2](https://user-images.githubusercontent.com/13793769/71104938-ed7a3980-21bc-11ea-84ca-9a1826bb159a.png)

Then we did the same comparison with the TrueType fonts on Ubuntu. And here is a considerable amount of jumping of cap height. This confirms the behaviour observed by the OP.
![IBM_Plex_Sans-TTF-waterfall-Firefox-Ubuntu-2](https://user-images.githubusercontent.com/13793769/71105443-dbe56180-21bd-11ea-96ad-7a8d7ce178ae.png)

This leaves the question: does the rasterizer on Ubuntu apply any of the TrueType hinting instructions that were put in the fonts at all?

To check this out we looked at the same comparison again but this time using the OTF versions with PostScript outlines. OTF fonts have a completely different method of hinting which is far less advanced than TT hinting. If any hinting information in the fonts is used then it should render visibly different from the TTF fonts. But on Ubuntu there is barely any difference in rendering. And most tellingly -- there are exactly the same errors in jumping cap height.
![IBM_Plex_Sans-OTF-waterfall-Firefox-Ubuntu-2](https://user-images.githubusercontent.com/13793769/71105930-aa20ca80-21be-11ea-89e2-f5ee8e653717.png)

Lastly, in order to check if this is behaviour unique to IBM Plex Sans, we also compared Ubuntu’s own typeface: Ubuntu designed and produced by Dalton Maag. And similar rendering errors in cap height can be observed here as well.
![Ubuntu-TTF-waterfall-Firefox-Ubuntu-2](https://user-images.githubusercontent.com/13793769/71107764-09cca500-21c2-11ea-841c-409c03abc139.png)

This leaves me to believe that the rasterizer in Ubuntu is:
• ignoring any hinting instructions in the font file
• probably applying some kind of auto-hinting when rendering fonts
• is not always able to render similar vertical dimensions in different fonts in the same way

**Comment by fthx** [comment]
Ok more remarks :

Using GNOME Tweaks, I can choose hinting (none, slight, medium, full).

Results using LibreOffice, IBM Plex Sans TTF size 11 (usual size for UI in Ubuntu) : 

NONE -> no issue
SLIGHT -> issue
MEDIUM -> no issue
FULL -> no issue

So, it's not an Ubuntu bug IMHO, if the bug is not Plex's fault.

**Comment by BoldMonday** [comment]
I think this proves that the exact rendering of the fonts cannot be controlled fully by the custom hinting information in the fonts themselves.

Therefore this issue is beyond the scope of the IBM Plex project.

**Comment by eWalthert** [comment]
We've just a received a screenshot from **Suse Tumbleweed Firefox** under **Gnome Waylan** that has the exact same issues. While Debian GNU Linux 8 is rendering fonts perfectly. 
If we deed to point fingers, it would indeed be GNOME that defines "SLIGHT" hinting as ignoring existing hints and auto-hinting the fonts on the fly. (evidentially pretty badly)
But according to this https://www.freetype.org/freetype2/docs/text-rendering-general.html, native hints _should_ be prioritised since 2015.
