### ISSUE TITLE
Sans and Mono underline thickness

### ISSUE THREAD

**Issue by vpicone** [IBM/plex#293]
The various sans/mono weights have substantially higher U-Thickness (60) compared to fonts of similar weights as well as compared Plex Serif (U-thickness 44).

![Screen Shot 2020-01-07 at 4 50 06 PM](https://user-images.githubusercontent.com/4078018/71936009-e4520c00-316d-11ea-9ad5-05dd35ca86b4.png)

Some browsers allow editing underline thickness through CSS, we can also explore that approach if the difference in thickness is intentional.

**Comment by BoldMonday** [comment]
Hi @vpicone , the difference in underline weight is intentional. The underline settings in the fonts are related to the weight of common horizontal elements in the shapes themselves such as the horizontal bars in `H` and `f` and the weights of serifs (if there are any).

<img width="535" alt="ibm-plex-serif" src="https://user-images.githubusercontent.com/13793769/72058693-cd77fa80-32d0-11ea-81be-c765e5d9c7d4.png">
<img width="566" alt="ibm-plex-mono" src="https://user-images.githubusercontent.com/13793769/72058694-cd77fa80-32d0-11ea-8313-7f3c507655b1.png">
<img width="500" alt="ibm-plex-sans" src="https://user-images.githubusercontent.com/13793769/72058695-cd77fa80-32d0-11ea-8ad7-aceb7242e317.png">

**Comment by vpicone** [comment]
@BoldMonday thanks for the extra info, it looks fine outside of the browser so I anticipate this is from some styling/browser bug. Thanks!
