### ISSUE TITLE
Add SCSS variables to control included fonts

### ISSUE THREAD

**Issue by connor4312** [IBM/plex#329]
This is a great font!

I'd like to include it in an Electron app. This means bundling the fonts. Unfortunately, the nice way to import fonts is to go through the `@ibm/plex/scss/ibm-plex.scss`, which will cause every font to be bundled, which has a pretty heavy disk size. There are nested files, but for example I can't import the "light" base font without also importing cyrillic fonts, which I don't need at the moment. And since I'm targeting Electron, I know I don't need `.woff` fonts, only `woff2`.

Of course, I could write create webpack rules that stubs the files I don't need via the `null-loader`, but a more graceful way would be appreciated 🙂 

It would be cool if the imported files were configurable via variables. For example, I could say:

```scss
$font-formats: woff2; // only import woff2
$font-weights: bold, regular;
$font-sets: base, latin1, latin2;
```

**Comment by mjabbink** [comment]
@vpicone

**Comment by tom-poulin** [comment]
The IBM Engineering Lifecyle Management (ELM) suite has also hit a size issue with bundling the fonts. At 129M, multiplied by each application in the suite, we've added over 1GB of girth to our download files, as reported in [534224: IBM i LICPGM builds are failing due to unexpected increase in IBMi workbench zip file](https://jazz.net/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/534224).

**Comment by vpicone** [comment]
@tom-poulin The next major version of Plex resolves this, you can try it out at `@ibm/plex@next`. There's an overhaul of the scss that's shipped with the package, but if you're authoring your own font-face declarations it should be good to go as a work around.

**Comment by tom-poulin** [comment]
@vpicone, is there an ETA for the release of this?
