### ISSUE TITLE
Full Language Version Provision Request

### ISSUE THREAD

**Issue by doloopo** [IBM/plex#397]
I love IBM Plex, and I hope it would be more international and universal. Like Noto Sans, providing a full language version as a non-tofu version that merges all the fonts of different languages would be great. It would make IBM Plex more suitable for a system displaying font in a multilanguage environment (I had just applied it to my system font, and it looks nice). As for non-tofu versions for those varieties like Thai Looped can also be separately provided. Though, when the Chinese SC/TC/HK/JP/KR version came out, it might be a little troublesome to handle so many different versions with OpenType/TrueType/Web and Hinted/Unhinted properties...

**Comment by BoldMonday** [comment]
I understand the desire for a version of Plex with all scripts merged into one font. The task itself is not trivial though. Currently the different language versions of Plex are optimised for their respective scripts. Trying to merge them together means that compromises have to be made. Also technically there will be many challenges because you will be reaching the limits of what the OpenType format is able to do. A third party made an attempt about a year ago and was unsuccessful.

**Comment by doloopo** [comment]
> 
> 
> I understand the desire for a version of Plex with all scripts merged into one font. The task itself is not trivial though. Currently the different language versions of Plex are optimised for their respective scripts. Trying to merge them together means that compromises have to be made. Also technically there will be many challenges because you will be reaching the limits of what the OpenType format is able to do. A third party made an attempt about a year ago and was unsuccessful.

Thanks.
And I found that Noto Sans is also separated into different language versions, and the Arabic version does not contain Thai scripts. While displaying as the system font, the system will automatically do fallbacks and complete the missing part using other language versions. It's the system's smartness that cheats me, making me think the font is unified... 🤣

**Comment by hakanai** [comment]
Noto Sans has both, actually. It does have individual ones with one language per font, but it also has large collections with multiple languages.
