### ISSUE TITLE
Character "C" not printing in Libreoffice Calc (OT family)

### ISSUE THREAD

**Issue by Giulioski** [IBM/plex#414]
Hello,
whenever we print the uppercase "C" char with IBM-Plex-Sans Opentype family then the char is not printed.
"c" lowercase is printing correclty in Opentype
Truetype is printing always correctly, upper- and lowercase.

Bug is always reproducible on every MS Windows System 7 upward.
Tested on black and color laser printer Kyocera in postscript mode.
Libreoffice Calc v. 7

This happens only with the "C" uppercase letter.

**Comment by BoldMonday** [comment]
I suggest to use the TTF versions of IBM Plex then. In terms of functionality OTF and TTF fonts are identical.

**Comment by Giulioski** [comment]
yes, but it's still a bug to resolve as soon as possible.
It's still possible to use the Truetype font but the screen output isn't so nice like the OT version.
I don't know why but the OT version has a smoother antialiasing result on screen.
Could someone investigate about this bug in the Opentype family?

**Comment by BoldMonday** [comment]
To establish whether this is a bug in the fonts, or in LibreOffice, or in the Kyocera printer driver, is hard to establish with the information given. And thei issue is hard to check from our side because of the specific configuration of software and the printing device. It would be very helpful if you can run additional tests and report back. If you can supply pictures of printouts that would be helpful too. When testing only use the OTF files hosted on this repository in order to have the latest version.

- Does the issue occur with **all weights and all styles** of IBM Plex (Sans, Sans Condensed, Serif, Mono)?
- Does the issue occur with other OTF fonts? ([Adobe Source Sans](https://github.com/adobe-fonts/source-sans) for example.)
- Does the issue occur if you print to your device from a different application than LibreOffice? (Windows Wordpad for example.)
- Does the issue occur if you print from LibreOffice to a different device?

**Comment by Giulioski** [comment]
Thank you mr. Paul for your effort but it doesn't belongs anymore to me mnaking this type of testing for more than 20 years now. I think here is more than 1 person that shouldn't sit on his. Breaking continously compatibility with 1000 of docs we already did has a cost that is not affordable. Those that changes always the font-names creating trouble and increasing the cost only for their "tech-ego" has definitely done for us.

**Comment by BoldMonday** [comment]
I’m sorry to hear that.

So far there have been no reports of OTF versions of Plex not printing correctly since their initial release four years ago. Given the amount of people using these fonts, and given the ubiquity of the letter in question, I can only assess that this issue must be tied very specifically to a particular configuration of hardware and software. And what part of that configuration is causing this issue remains to be seen.

Therefore I hope you understand that without additional information there is not much we can do for now.
