### ISSUE TITLE
IBM Plex doesn't show up in Apple Pages, Keynote and Numbers on macOS Monterey with German locale

### ISSUE THREAD

**Issue by arnogramatke** [IBM/plex#419]
I am running macOS Monterey 12.1 set to German with the IBM Plex Fonts v6.0.0 installed as TTF.

When running Apple Pages, Keynote or Numbers the only Plex font that shows up in the font list is "IBM Plex Sans JP". The other fonts dont' show up, but can be selected from the font popup (Cmd+T). In this font popup, the font collection "Deutsch" (German) is preselected. In this selection, the only IBM Plex font is "IBM Plex Sans JP". The others don't show up there.

They show up in the "All fonts" selection, though.

When I check the IBM Plex fonts in Apple's Font Book app, only the IBM Plex Sans JP font contains "Deutsch" (German) in the "Sprache" (Language) section. For the others fonts, the "Sprache" section is either empty or doesn't contain German.

It looks like the Apple apps only present the font collection that corresponds to the system's locale.

I am not sure, if this is only an issue on macOS systems which are set to German, but it would be great, if German could be added to the language section in the font definition.

**Comment by BoldMonday** [comment]
Thanks for reporting the issue.

This is puzzling since fonts technically cannot identify themselves to support a particular language. All information about supported languages in Apple’s Font Book is based on Apple’s own heuristics. Therefore this appears to be a bug in macOS Monterey.

Out of curiosity: can you post some Font Book screenshots to illustrate the issue?

**Comment by arnogramatke** [comment]
The field "Sprache" (Language) is empty for IBM Plex Sans:
<img width="1552" alt="Font Book IBM Plex Sans" src="https://user-images.githubusercontent.com/27431532/149671320-d688455b-a478-4601-bffa-ca79973cc063.png">

The field "Sprache" (Language) contains many languages for IBM Plex Sans JP:
<img width="1552" alt="Font Book IBM Plex Sans JP" src="https://user-images.githubusercontent.com/27431532/149671375-8361ebef-8a5d-4d0c-9777-d883b2a387d0.png">

This is the smart collection "Deutsch" (German) which seems to the one used by Apple's Pages, Keynote and Numbers apps. IBM Plex Sans JP is the only from the IBM Plex font family.
<img width="1552" alt="Font Book German Collection" src="https://user-images.githubusercontent.com/27431532/149671509-1c9560f0-6b32-4789-8cea-aa82562661b2.png">

This is how this collection is shown in Pages:
<img width="291" alt="Apple Pages Font List" src="https://user-images.githubusercontent.com/27431532/149671547-332aac71-c1f3-4bf6-ac09-f469ee46433e.png">

**Comment by BoldMonday** [comment]
Thank you for creating the screenshots. Absolutely baffling why the field with _Sprache_ remains completely empty...

We will try to reach the appropriate people at Apple to submit the bug. Hopefully they can fix this soon.

**Comment by alohawolf** [comment]
This also impacts users with the English Locale too.

**Comment by BoldMonday** [comment]
We discovered that one way to circumvent this problem is to use macOS own font panel that can be invoked from the top menu under: **Format** > **Font** > **Show Fonts**.

From the macOS font panel choose **All Fonts** in the list on the left.
![image](https://user-images.githubusercontent.com/13793769/154287867-0e5e7776-9103-490b-a763-e2eabbf1b2f8.png)

**Comment by lukipedia** [comment]
Also having this issue in macOS 12.3.1 with English as the system language. Have the .otf versions of the files installed.

Plex shows up in the macOS font browser (cmd+T) and in the font book, but will not show up in Keynote, Pages, Preview, or any of the other Apple productivity apps. The fonts show up in e.g. Microsoft Word, but the selection is bizarre:

<img width="505" alt="Screen Shot 2022-04-04 at 22 53 39" src="https://user-images.githubusercontent.com/103016209/161675655-c58ca0ff-54dc-4040-a656-d0b5851c000c.png">

**Comment by hbuschme** [comment]
Same problem here (macOS 12.2.1, locale English). A Keynote presentation template I regularly use now tells me "This presentation has missing fonts." When replacing the fonts in the build-in dialogue box, the fonts show up with completely different font-names (e.g., "IBM Plex Mono Medm" instead of "IBMPlexMono-Medium").

<img width="509" alt="Screenshot 2022-04-22 at 12 11 16" src="https://user-images.githubusercontent.com/122398/164687598-996ed64c-2612-441c-8f5c-866fa4a77beb.png">

**Comment by kenmcd** [comment]
> Same problem here (macOS 12.2.1, locale English). A Keynote presentation template I regularly use now tells me "This presentation has missing fonts." When replacing the fonts in the build-in dialogue box, the fonts show up with completely different font-names (e.g., "IBM Plex Mono Medm" instead of "IBMPlexMono-Medium").
> 
> <img alt="Screenshot 2022-04-22 at 12 11 16" width="509" src="https://user-images.githubusercontent.com/122398/164687598-996ed64c-2612-441c-8f5c-866fa4a77beb.png">

It appears the font names were changed internally between v5.2.1 and v6.0.0.
And your template was created with v5.2.1.

Examples for IBM Plex Sans - Medium
Font v3.2 from package v5.2.1
![IBM Plex Sans v3 2 (5 2 1)](https://user-images.githubusercontent.com/844920/164815847-3f57e9fd-2b38-47a2-a7f8-f2fe96aca922.png)
Font v.3.3 from package v6.0.0
![IBM Plex Sans v3 3 (6 0 0)](https://user-images.githubusercontent.com/844920/164815905-87d16805-2f3d-4aa7-8dbb-33e33cbc5423.png)

Those name differences are causing a mis-match on the fonts.

**Comment by rorynl** [comment]
I'm using a Mac Studio with Monterey 12.4 and the font manager Typeface 3. I installed the IBM Plex fonts today to the directory that I use for fonts with Typeface 3. I've only checked Apple Pages, but Pages does not show any of the IBM Plex fonts as available. The is the only font that I'm experiencing this with.

**Comment by BoldMonday** [comment]
> It would be a good idea to fix this. I'm OK with the workaround, but I spent a good deal of time trying to figure out what the problem is before doing a search and finding this thread.

@rorynl I agree and the fix should come from Apple. Because it worked on a previous version of Monterey.
The problem is not unique to IBM Plex -- there are other fonts out there affected by this bug as well.

**Comment by BoldMonday** [comment]
Yes, we’re laying this off on Apple because we know exactly what the cause is.

The Plex fonts contain a `meta` table for specifiying meta information what scripts and languages are supported.
https://docs.microsoft.com/en-us/typography/opentype/spec/meta

This meta table is specially added because the Plex fonts are supporting many different languages and many different scripts over lots of different files. This table can help in accessibility. Windows is using information from it for showing sample strings for example.

Monterey introduced a bug in Apple’s own heuristics for determining language support in fonts. These heuristics do not work anymore on all fonts containing a `meta` table. When we discovered this we filed a bug report at Apple explaining in detail the cause.

**Comment by rorynl** [comment]
@BlueMonday:

> we know exactly what the cause is.

I'm not trying to give you a hard time, but the complete lack of communication about this is hard to comprehend. On the upside, it's great to find out after 4½ months of this thread, which one has to search for to find, what the problem is.

Here's a question. Do you think it might be a good idea to tell people who are downloading IBM Plex about this problem and what the workaround is? You know, so they don't waste their time trying to figure out why Plex doesn't show up on their font lists, which is kinda basic to using a font, and whether it's a problem with the font itself or with their font manager? Yeah, before I found this thread one of the things that I was considering was opening a ticket with Typeface Pro 3, the people who make my font manager.

When I went to IBM's Plex site yesterday and selected "Get Plex", the screen capture below shows what I was taken to. Plex was just recently updated to 6.0.2. I downloaded and installed it. There is not a single word about this problem anywhere on the page. Not one.

The way that this is being handled defies common sense. What's IBM's attitude about this? The font is "free", so live with it?

![Screenshot 2022-05-27 at 12 59 27](https://user-images.githubusercontent.com/23560683/170755846-51360416-caa4-49d5-bdb5-0d4054540296.png)

**Comment by BoldMonday** [comment]
> The phrase "completely unprofessional" comes to mind

@rorynl This is completely uncalled for and I strongly suggest to take a deep breath here.
As developers and maintainers of Plex we are not responsible for Apple’s slow response to bug reports.

Since Plex was introduced to the world in 2018 it has been in use by well over one hundred thousand users who have been able to use these fonts on a daily basis on a multitude of platforms and environments. There are very few other typefaces out there that match the scope of Plex in terms of amount of styles and coverage of global languages. On top of that, Plex has also received numerous design awards.

**Comment by twardoch** [comment]
I second @BoldMonday — the fonts follow the OpenType specification, and the `meta` table was in fact first proposed by Apple. If one operating system or app maker breaks handling of valid fonts in some release, it should be up to that vendor to »unbreak« this. 

This is not the first and not the last time that some software maker breaks the way certain OpenType fonts work in their OS or app. This happens quite often. Introducing hacks and workarounds to shipping fonts every time this happens would mean that font vendors wouldn’t be able to do the actual font development.

If a font vendor manages to isolate the problem and reports it via the appropriate channels (this rarely involves the phone these days) — that’s the professional thing to do, and quite often that’s pretty much the best they can do.

**Comment by rorynl** [comment]
> @BoldMonday As developers and maintainers of Plex we are not responsible for Apple’s slow response to bug reports.

Please don't be defensive. One of the reasons that I'm referring to IBM in my posts, and not to your company  as its contractor, is to try to keep this from bring personal. In the post to which you're responding, I wasn't even talking about Apple's processing of the bug report. Indeed, the underlying assumption of my post is that IBM _can't_ control the timing of that, (although I must say, I would have thought that IBM and Mike Abbink have more pull that you seem to suggest :)

I've said what I've got to say, and I stand by every word of it. The way that this is being handled flies in the face of common sense. It has caused me, and I'm sure many others, a completely unnecessary waste of time. Either IBM will take up my suggestion about informing people of this problem at the time of download, or it won't. I think that whether it does depends on whether IBM cares about the people who it is encouraging to download this typeface.

I don't see what any of this has to do with whether Plex is a good typeface (I think that it is) or how many awards it's won.

I'm left with the impression that those of us who don't hang out at GitHub and spend our lives reading its "Issues" threads simply don't count :)

**Comment by BoldMonday** [comment]
Apple has fixed the issue in macOS Ventura, and correctly determines language support again in IBM Plex fonts containing a meta table.

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/13793769/201889690-42a6e344-9ced-4de3-b25a-24be6d15c7fa.png">

**Comment by unikitty37** [comment]
Thanks, @BoldMonday — I don't suppose Apple has given any clue as to whether they're going to backport that to Monterey, for the benefit of users who can't upgrade yet?

(My bet is no, because Apple, but I live in hope 😁)

**Comment by BoldMonday** [comment]
@unikitty37 Knowing Apple I would not hold my breath...
