### ISSUE TITLE
Support proportional Cyrillic, Greek in Plex Sans JP

### ISSUE THREAD

**Issue by akihironagai** [IBM/plex#428]
<img width="1756" src="https://user-images.githubusercontent.com/77012577/153548495-26b6b93e-e198-4a72-b5e2-6fa3d59ba86e.png">
<img width="1747" src="https://user-images.githubusercontent.com/77012577/153548484-9ce5378f-9ceb-4967-ab81-c5d9362e3290.png">

In Japanese documents, Cyrillic and Greek characters rarely appear, but they are sometimes used to write the names of Russian people, for example.

However, IBM Plex Sans JP contains full-width Cyrillic and Greek characters, so it is not beautiful.

Therefore, it deletes the Cyrillic and Greek monospaced fonts from IBM Plex Sans JP and replaces them with proportional fonts.

**Comment by BoldMonday** [comment]
@mjabbink This question is for the original designers of Plex JP to answer. I don’t know the rationale why they’ve made these glyphs full width.

**Comment by mjabbink** [comment]
@BoldMonday This is an oversight and should get resolved. Cyrillic and Greek should have maintained their spacing from IBM Plex Sans.

**Comment by AutismIsMySuperpower** [comment]
I think the reason why the Greek and Cyrillic in the proportional is because in the Japanese Google fonts, they're also full-width. Here's an example:
![Screenshot (76)](https://user-images.githubusercontent.com/92538982/161438363-9e0dba74-2969-4783-8d06-b0779b34205f.png)
 *(But seriously they should be proportional.)*

**Comment by NightFurySL2001** [comment]
Traditionally Japanese (and Chinese too) treated Cyrillic and Greek as double-byte characters (in EUC/ISO 2022 encoding), so their appearance is made such that it will take out a full width character space (normal ASCII is one-byte and half width); a full set of full-width ASCII is repeated in double-byte range too so this difference is made to make it more visible.

However, since there is no more difference now, it is more beneficial to update Cyrillic and Greek to proportional width. This should be noted for the upcoming Chinese font too.

**Comment by BoldMonday** [comment]
Fixed in https://github.com/IBM/plex/releases/tag/%40ibm%2Fplex-sans-jp%401.0.0
