### ISSUE TITLE
There is spacing issue when we generate greek lang pdf

### ISSUE THREAD

**Issue by doonvipul** [IBM/plex#485]
1. There is spacing issue when we generate greek lang pdf, can you please let me know which font to be used or I can use any out of these ?
![image](https://user-images.githubusercontent.com/51817470/194475852-c38c4fc0-673b-4a93-be59-0785b19d3062.png)

2. Is there any issue, if I use IBM-Plex-Sans-JP and IBM-Plex-Sans together.  I need to generate both Japanese and Greek languages PDF using Apache FOP Api.

**Comment by doonvipul** [comment]
Is there any slack support channel, to discuss the issue

**Comment by BoldMonday** [comment]
1. You can use any of these styles. This question was already answered in https://github.com/IBM/plex/issues/483
> **IBM Plex Sans** (without any suffix) supports extended Latin, extended Cyrillic, and monotonic Greek.
All other members of the Plex Sans family are specifically to support Hebrew, Arabic, Devanagari, Thai, Korean (KR) and Japanese (JP).

2. Technically it is possible to use multiple styles of Plex together because they all have distinct names: if you install **IBM Plex Sans JP** together with **IBM Plex Sans** on your system then you will see seperate entries in the font menu for them.

3. This repository is only about the development and maintenance of the IBM Plex typeface family. It does not deal with technicalities how to implement Plex on various platforms. We don't know anything about Apache FOP or how it deals with fonts. But I’m sure there are other places for that.
