### ISSUE TITLE
23/12/2022 Suggestions

### ISSUE THREAD

**Issue by rioxeliem** [IBM/plex#500]
Suggestion :
1. Add Serif bars on "4" at IBM Plex Serif (Like Cambria font). Non-Serifed "4" will be a stylistic set.
2. Add Proportional Lining and Proportional Old-Style Figures In IBM Plex Sans without Serifs on "1".
3. Add Non-Serifed "7" as Stylistic set at IBM Plex Sans and IBM Plex Mono.
4. Add Non-Serifed "I" as Stylistic set at IBM Plex Sans.
That's all, Hopefully it will be great idea

**Comment by BoldMonday** [comment]
Given that all sub-families of Plex consist of eight weights in roman and italic styles these requests are not a trivial task to undertake. Especially when the creation of kerning for proportional figures has to be considered as well.

Since these suggestions are primarily cosmetic in nature, and since the design of the current numerals has been chosen very deliberately, I suggest to create your own custom fork.
