### ISSUE TITLE
Sans Text & Regular, hinting: hyphen thicker than other horizontal strokes

### ISSUE THREAD

**Issue by ortoslon** [IBM/plex#509]
In some sizes above 15 ppem Sans Text's hyphen (the ASCII one -) is noticeably thicker than the em-dash and horizontal strokes of e, z, H. Mono Text doesn't have this problem.

Side by side in Chrome 109 on Win10:
https://github.com/IBM/plex/blob/003b8b0a6f56acd78e8fa78ddf471f71412e18b4/IBM-Plex-Mono/fonts/complete/ttf/IBMPlexMono-Text.ttf and https://github.com/IBM/plex/blob/003b8b0a6f56acd78e8fa78ddf471f71412e18b4/IBM-Plex-Sans/fonts/complete/ttf/IBMPlexSans-Text.ttf
![image](https://user-images.githubusercontent.com/79928123/216711773-844aee77-7d4a-4cdf-8782-64c203288513.png)

**Comment by ortoslon** [comment]
Same with https://github.com/IBM/plex/blob/003b8b0a6f56acd78e8fa78ddf471f71412e18b4/IBM-Plex-Sans/fonts/complete/ttf/IBMPlexSans-Regular.ttf

![image](https://user-images.githubusercontent.com/79928123/216762985-0e825e30-fa56-48de-ab2f-ef4c33c06914.png)

**Comment by BoldMonday** [comment]
If you check the actual outlines of those glyphs then you will see that `hyphen` is always thicker than most other dashes. That is by design. Because of its short length, a hyphen needs to be heavy enough to be clearly recognisable.

The difference in weight between hyphen and dashes can sometimes disappear in small sizes because of rounding to whole pixels. We don't see any issue with that.

**Comment by ortoslon** [comment]
Thanks for the explanation. I was just surprised in comparison with other well-hinted monolinear fonts:
![image](https://user-images.githubusercontent.com/79928123/216769439-59b90272-84f5-40b2-82d6-f24f2bf758d7.png)
