### ISSUE TITLE
Support For SC ( Simplified Chinese )

### ISSUE THREAD

**Issue by FabianNicola** [IBM/plex#582]
Hey! Anyone knows when support for IBMPlexSans Simplified Chinese will be available ? I see that support for Traditional Chinese is already in place. When is SC supposed to come out?

**Comment by mjabbink** [comment]
@FabianNicola We’re hoping Q3, but latest Q4 2024.

**Comment by BobH-Official** [comment]
@mjabbink I have some questions, in the first Chinese release, will all characters be in the Chinese style or just copy from the Japanese if they were already there?
For example, this character(燹 U+71F9), in this issue, https://github.com/IBM/plex/issues/580. It has small different at the bottom part (火).
![image](https://github.com/user-attachments/assets/420d104a-a263-4d67-9445-5bdc61c0a5bf)

And will there only be Chinese TC and Chinese SC release, instead of Chinese TC (Taiwan), Chinese TC (Hong Kong) and Chinese SC (China)?

**Comment by NightFurySL2001** [comment]
@BobH-Official 
1. The dot difference of 火 does not exists in printing fonts (eg songti/heiti) for Chinese. If you reference 《通用规范汉字表》, you will see that the left dot of 火 indeed goes from top right to botton left (like 丿), which mean for this particular character SC and JP are expected to share the same glyph.
2. The Traditional Chinese community strong vote against separating TC (Taiwan Education) and TC (Hong Kong Education/Reference Glyphs). They are only suitable for educational usage, and in a grotesque font design like IBM Plex, the traditional printing form (旧字形) is more matching the intended design. See #346 for more information on discussion.

**Comment by BoldMonday** [comment]
> And another question, will that be a unified Chinese font, but display SC and TC glyphs based on `font-feature-settings`, for example `ss01` to switch between them. This may be useful for website that provided SC and TC i18n.

There will be separate releases for Plex Sans TC and Plex Sans SC.

**Comment by Palke** [comment]
https://www.npmjs.com/package/@ibm/plex-sans-sc
