### ISSUE TITLE
IBM Plex for iOS 18

### ISSUE THREAD

**Issue by vd2org** [IBM/plex#596]
iOS 18 has a new font management feature and fonts could be installed from the App Store. 
Please consider to provide a package for iPhone. I'd like to use it. Thanks!

**Comment by BoldMonday** [comment]
Are there any pointers to this new font management feature in iOS 18? And how it different from the current situation?

Fonts can be installed on iPhones and iPads since iOS 13 albeit in a very complicated manner.
Essentially fonts can only be installed from a dedicated app that has to be available from the App Store.
Naturally Apple has to approve that app, and charges money for it.
