### ISSUE TITLE
Consider a more curvy tilde

### ISSUE THREAD

**Issue by gnuvince** [IBM/plex#99]
I find that the tilde character in IBM Plex Mono (`~`) is not curvy enough, and at low font sizes could be mistaken for a dash or a hyphen.

**Comment by soviet-man** [comment]
Agreed

**Comment by BoldMonday** [comment]
Good suggestion. We will consider it for a future update.

**Comment by iandoug** [comment]
Please, especially the monospace version.

**Comment by jonathonf** [comment]
Just to confirm, this isn't just a possiblity - at some sizes (and/or with certain hinting, I saw it under Ubuntu but not under Manjaro) it's indistinguishable from a dash.

**Comment by iandoug** [comment]
FWIW the Hack guys having been looking at the issue of confusing glyphs, and they built a tool.

https://github.com/source-foundry/Hack
https://github.com/source-foundry/compare-typefaces
https://source-foundry.github.io/compare-typefaces/index.html

I use tilde as a divider in text files (eg for loading into databases, as opposed to a comma or tab) and thus am somewhat pedantic about it looking very different to a dash. This is for monospace version... the use cases on normal sans may be different and not so critical. I think the issue really is "is this tilde supposed to sit on top of an 'n', or does it have other uses requiring it to look different to ñ " ?.....

For programmers/users of monospace, I don't think having stand-alone tilde look like ñ is important, just like having ^ look like ê is not important.

Cheers, Ian

**Comment by twardoch** [comment]
The standalone ~ or ^ are indeed completely different characters than the diacritical marks used over letters. Fortunately, Unicode takes care of that (there are special codepoints for combining tilde or circumflex where those signs can be designed small and so that they look well over letters). The ASCII "diacritics" these days are used in different contexts, often indeed in computing, and should be designed in a more prominent way so they are easily distinguishable as standalone characters.

**Comment by iandoug** [comment]
@twardoch , yes I know, I was just leaving open the possibility that the designers wanted the stand-alone tilde to look like the "diacritic" version. It's the only reason I can think of why so many fonts make the stand-alone tilde almost a dash.

**Comment by chdiza** [comment]
I have abandoned Plex Mono for coding because the tilde looks like a dash at non-huge sizes.  A pity.

**Comment by mjabbink** [comment]
We should improve the Tilde

**Comment by chdiza** [comment]
@BoldMonday I commented in February about v2.0 because even with 2.0, at 11pt on macOS, the tilde and en-dash are basically indistinguishable.  At 10pt, it's very hard to tell the tilde from a regular dash.  At 12pt it's close enough to an en-dash that mistakes are inevitable.  This is wrecking Plex Mono as a coding font.

**Comment by chdiza** [comment]
This, e.g., is the tilde on macOS 10.13.6 at 11pt:

![tilde](https://user-images.githubusercontent.com/3311113/47852487-4cf76900-ddb2-11e8-8d30-d2d6a8ae045e.png)

I have to stare awfully close at that to see that *maybe* it's a tilde.

**Comment by mjabbink** [comment]
@boldmonday I agree we should improve. Extending terminals and increasing the size a bit could do the trick.

**Comment by mjabbink** [comment]
Well, maybe not size but a more expressive tilde would be a nice thing and solve the issue.

**Comment by mjabbink** [comment]
@BoldMonday
